{% set name = "aiida-crystal17" %}
{% set version = "0.6.0b3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0ffc7681e52329d6a53c220d9064d4cf10875e319000d9564efed23d5036d979

build:
  number: 0
  entry_points:
    - mock_runcry17 = aiida_crystal17.tests.mock_runcry17:main
    - mock_gulp = aiida_crystal17.tests.mock_gulp:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  skip: True  # [win or py > 36]

requirements:
  host:
    - pip
    - python
    - reentry >=1.3.0
    - setuptools
  run:
    - aiida-core ==1.0.0b3
    - ase >=3.12.0,<4.0.0
    - ejplugins >=0.9.7
    - graphviz
    - jsonextended >=0.7.10
    - numpy ==1.16.1
    # TODO these are the requirements in aiida-core[atomic_tools]
    # but pycifrw only available from 4.3 on conda-forge
    # - pycifrw ==4.2.1  # [py <= 27]
    # - pycifrw ==4.4  # [py > 27]
    - pycifrw ==4.4
    - python
    - ruamel.yaml
    - six
    - spglib >=1.10.0,<2.0.0

test:
  imports:
    - aiida_crystal17
    - aiida_crystal17.calculations
    - aiida_crystal17.calculations.tests
    - aiida_crystal17.cmndline
    - aiida_crystal17.data
    - aiida_crystal17.data.tests
    - aiida_crystal17.gulp
    - aiida_crystal17.gulp.calculations
    - aiida_crystal17.gulp.calculations.tests
    - aiida_crystal17.gulp.cmndline
    - aiida_crystal17.gulp.parsers
    - aiida_crystal17.gulp.parsers.tests
    - aiida_crystal17.gulp.potentials
    - aiida_crystal17.gulp.potentials.tests
    - aiida_crystal17.immigration
    - aiida_crystal17.parsers
    - aiida_crystal17.parsers.tests
    - aiida_crystal17.symmetry
    - aiida_crystal17.tests
    - aiida_crystal17.tests.gui_test_files
    - aiida_crystal17.tests.gui_test_files.inputs
    - aiida_crystal17.tests.gui_test_files.outputs
    - aiida_crystal17.tests.gulp_input_files
    - aiida_crystal17.tests.gulp_output_files
    - aiida_crystal17.tests.input_files
    - aiida_crystal17.tests.input_files.sto3g
    - aiida_crystal17.tests.input_files.tzvp
    - aiida_crystal17.tests.output_files
    - aiida_crystal17.validation
    - aiida_crystal17.workflows
  commands:
    - mock_runcry17 --test
    - mock_gulp --test

about:
  home: https://github.com/chrisjsewell/aiida-crystal17
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: AiiDA plugin for running the CRYSTAL17 code
  doc_url: https://aiida-crystal17.readthedocs.io
  dev_url: https://github.com/chrisjsewell/aiida-crystal17

extra:
  recipe-maintainers:
    - chrisjsewell
